### ISSUE TITLE
Fitting for scattering parameters is broken

### ISSUE THREAD

**Issue by kmjc** [CHIMEFRB/fitburst#81]
I ran into a couple of errors in `derivative.py` trying to fit for scattering

a) `deriv_model_wrt_scattering_index` 
I'm not sure these two lines https://github.com/CHIMEFRB/fitburst/blame/57a86a8ae747b08071be4e4ab3f76f325294a293/fitburst/routines/derivative.py#L747-L748 need to exist since `spectrum` is overwritten immediately below? If they are needed then line 747 throws a couple of `NameError`s

I think you also need to add 
```
burst_width = parameters["burst_width"][component]
```
or something similar since `burst_width` throws a `NameError` too.

b) `deriv2_model_wrt_burst_width_scattering_index`
`log_freq = np.log_freq_ratio` -> `log_freq = np.log(freq_ratio)`

**Comment by emmanuelfonseca** [comment]
this has been fixed in #84.
