### ISSUE TITLE
unused variable indicates a bug

### ISSUE THREAD

**Issue by expnn** [CHIMEFRB/fitburst#83]
The variable `current_sc_time_scaled` is unused. Is it a bug?
https://github.com/CHIMEFRB/fitburst/blob/57a86a8ae747b08071be4e4ab3f76f325294a293/fitburst/analysis/model.py#L219

**Comment by emmanuelfonseca** [comment]
hi @expnn, this indeed looks to be an unused piece of code. good catch! i'll remove this in an upcoming updated to `main` and will close this issue once i do.

**Comment by emmanuelfonseca** [comment]
this bug has been addressed in #86 .
